language: elixir
elixir: 1.5.0
otp_release: 20.0

env:
  - MIX_ENV=test

cache:
  directories:
    - _build
    - deps

before_script:
  - mix deps.compile

script:
  - mix compile --warnings-as-errors
  - mix test
